adding-more-example-code
umairian/node-boiler-plate-app pull request #1
Opened 2022-12-31 09:43 UTC by umairian

This PR consists of the following work:
- Console statements modified.
- Migration and model of `blogs` table added.
- User model name changed to `user.js` and migration name updated too.
- Eslint config file added and other configurations modified.
- Association between `users` and `blogs` added.
- Example routes and controllers added for `users` and `blogs`.

2023-01-01 04:28 UTC, noorarman requested changes
@umairian reviewed PR thoroughly, well remember you can consider them my suggestions i mean that's how i would do them.

2023-01-01 04:28 UTC, noor-ul-amin0 commented on app.js
> +    strict: true, //	Enables only accepting arrays and objects
@umairian as we know both `inflate` and `strict` are true by default so we can skip those.

2023-01-01 04:28 UTC, noor-ul-amin0 commented on controllers/blog.js
> +};
@umairian for handling async functions the try-catch block is being repeated in every controller function why not we create a reusable utility called `catchAsyncHandler` and just wrapped our controller functions in it? Then can use it throughout the application.

2023-01-01 04:28 UTC, noor-ul-amin0 commented on database/migrations/20221231090036-create-users-table.js
>        },
@umairian it will be good to make the emails unique and they should be unique, for that we can put a unique option in the column e.g
 ```
email: {
        type: Sequelize.STRING,
        allowNull: false,
        unique: true
      },
```

2023-01-01 04:28 UTC, noor-ul-amin0 commented on middlewares/authenticate_user.js
> +    }
@umairian we can create a proper Error handler class for handling errors, the beauty is we can allow the constructor to accept as many options as possible. So for instance if the global Error handler class is AppError then we can use it like.
`if(!user) return next(new AppError(errorMessage,statusCode))`

2023-01-01 04:28 UTC, noor-ul-amin0 commented on database/migrations/20221231090054-create-blogs-table.js
> +      },
@umairian what is the need of archived column?

2023-01-01 04:28 UTC, noor-ul-amin0 commented on models/blog.js
> +    },
@umairian if the purpose of archived field is merely soft deletion then fortunately `sequelize` has a schema option called `paranoid` which hassle out the soft deletion for us.
This would add a `deletedAt` column.
It has the following advantages:
1. We can perform  destroy operations on Models and instances by directly destroying them e.g `blog.destroy()` it won't delete the record rather will add timestamp(`deletedAt`) in the row(s).
2. We can query without explicitly adding any where condition to skip the deleted records. e.g `await Blogs.findAll();`

2023-01-01 04:28 UTC, noorarman commented on models/user.js
>      },
@umairian we can add a isEmail validation on email field using.
```
email: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        isEmail: { msg: "Please enter a valid email" },,
      },
    },
```

2023-01-01 04:28 UTC, noorarman commented on routes/user.js
> +  .put(controller.update);
@umairian if we see we need to authenticate the user for each protected route for that we are repeating `authenticateUser` mw in each route. It's best to use it only once and all the proceeding routes will go through it e.g:
```
router.all('/:userId/*,authenticateUser)
router.use("/:userId/blogs", blogRouter);
router
  .route("/:userId")
  .get(controller.getOne)
  .put(controller.update);
```

2023-01-01 04:28 UTC, noorarman commented on controllers/user.js
> +      );
@umairian we know that user in the req object is already a sequelize instance so we don't need to update the user by Model rather we can update the instance directly e.g
await req.user.update(payload,options)

2023-01-01 04:28 UTC, noorarman commented on routes/blog.js
> +router.route("/").post(controller.create).get(controller.get);
@umairian one of the best practice of REST API is resource naming convention, e.g it'll be good and make sense to both beginners and seniors if we make `createOne` and `getAll`.

2023-01-20 05:44 UTC, uzair004 requested changes
@umairian Nice boilerplate, can't remember sequelize specific stuff, left a general review. highly recommend dependency injection one.

2023-01-20 05:44 UTC, uzair004 commented on .eslintrc.json
> +  "rules": {}
some handly eslint rules for you.

- won't allow console logs before creating PR or deployment
- ternary not allowed (not readable) you can disable sometime for simple use
- no plus plus , prefer array methods over for loop
- no unused vars
- no undefined, use null instead
- prefer const (auto detect if not resued)
- allow console error logs


```js
  rules: {
    'no-console': ['error', { allow: ['error', 'warn'] }],
    'no-ternary': 'error',
    'no-return-await': 'error',
    'no-plusplus': 'error',
    'no-lonely-if': 'error',
    'no-unused-vars': 'error',
    'no-undef': 'error',
    eqeqeq: ['error', 'always'],
    'no-var': 'error',
    'prefer-const': 'error',
  },
```

2023-01-20 05:44 UTC, uzair004 commented on controllers/blog.js
> +          model: Users,
Recently I came across pattern for different file for each controller
here is a rough organizational overview

```
controllers
 |__ createUser.js
 |__ deleteUser.js
 |__ index.js // here import all controllers & export them,,, willl be imported from this file into other files
```

```
controllers
|_index.js
|__ user
        |_ createUser.js
        |_ deleteUser.js
 |__ order
        |_ createOrder.js
```

```js
const makeCreateUser = ({moment, whatever_depedency}) => {
    return async function createUser(req, res) {
          ...... do all stuff
          
    }
}
module.exports = {makeCreateUser}
```
index.js
```js
const {makeCreateUser} = require('./createUser')
const createUser = makeCreateUser({moment, whatever_depdency})

module.exports = {createUser, updateUser....}
```

It will keep stuff organized, code conflict could result in single controller problem only

2023-01-20 05:44 UTC, uzair004 commented on controllers/blog.js
> +      return res.status(200).send({ blogs });
I will really like to control headers for all response from single place, when needed later we can change/update/remove headers from single place & it will be updated throughout app. i.e CORS headers.
```js
const { createSuccessResponseHeaders } = require('../util/util');


res.send(statusCode,createSuccessResponseHeaders() ) // I don't remember what headers express add to response, need to look into how we can control express headers ourselves.
```

2023-01-20 05:44 UTC, uzair004 commented on controllers/blog.js
> +      console.log(err);
`console.error()` will provide better stack trace I guess, plus eslint rules will allow it.

2023-01-20 05:44 UTC, uzair004 commented on controllers/blog.js
> +        .message(err.message || "Something went wrong!");
How about storing these error message in a place i.e constants/resposes.... later if need we can change in single place `Something went wrong` to `system error` & it will work,,,,, nothing major but good to have

2023-01-20 05:44 UTC, uzair004 commented on controllers/user.js
> +      const { user } = req;
I assume you are calling database in middleware & passing data to controller. If not needed you should avoid db calls from middleware.
if you need to check something i.e access embeed that permission in user token. & check there,,,, can't avoid always but generally good idea as random requests won't result in db calls.

2023-01-20 05:44 UTC, uzair004 commented on controllers/user.js
> +      const createdUser = await Users.create({
There isn't another user var in this file, so prefer `user` concise & precise.

2023-01-20 05:44 UTC, uzair004 commented on models/blog.js
> +
Can we import individual method from moment.
```js
const {unix} = require('moment')
```
that would be nice & neat

2023-01-20 05:44 UTC, uzair004 commented on database/migrations/20221231090036-create-users-table.js
>          type: Sequelize.ENUM("Pending", "Approved", "Rejected"),
keep these enums somewhere in constants. I think there is a way to directly insert array of enums in sequelize, don't remember exact thing.
But you can import Enums array herere & spread it,,,, `...typeArr`

2023-01-20 05:44 UTC, uzair004 commented on controllers/blog.js
> +      const createdBlog = await Blogs.create({
`const blog`

2023-01-20 05:44 UTC, uzair004 commented on controllers/blog.js
> +      return res.status(200).send({ blog: createdBlog });
`send({blog})`

2023-02-02 13:17 UTC, merged